Repository elastic/elastic-agent-shipper, pull requests merged in 2022-08, with the labels that each got.

#75 Add support for diskqueue
  NOTICE.txt
  config/config.go
  dev-tools/templates/notice/overrides.json
  go.mod
  go.sum
  output/console.go
  queue/config.go
  queue/queue.go
  queue/queue_test.go
  server/run.go
  server/server.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#76 Implement the shipper gRPC server
  NOTICE.txt
  go.mod
  go.sum
  queue/queue.go
  server/controller_client_test.go
  server/run.go
  server/server.go
  server/server_test.go
Labels: Team:Elastic-Agent-Data-Plane

#85 [automation] Update go release version 1.18.5
  .github/workflows/golangci-lint.yml
  .go-version
  .golangci.yml
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, dependency, backport-skip

#90 Add `StrictMode` with event validation
  cmd/cmd.go
  config/config.go
  controller/controller_client.go
  controller/controller_client_test.go
  controller/run.go
  server/config.go
  server/server.go
  server/server_test.go
Labels: Team:Elastic-Agent-Data-Plane

#91 Add blocking on the first event in the batch
  queue/queue.go
  queue/queue_test.go
  server/server.go
  server/server_test.go
Labels: Team:Elastic-Agent-Data-Plane

#94 Add a detailed README and clean up the configuration file
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/flaky-test.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  config/config.go
  controller/run.go
  docs/elastic-agent-shipper-arch.png
  elastic-agent-shipper.yml
  queue/config.go
  server/config.go
Labels: Team:Elastic-Agent-Data-Plane

#73 Expand mage and add build options
  .ci/Jenkinsfile
  .gitignore
  .goreleaser.yaml
  NOTICE.txt
  dev-tools/common/common.go
  dev-tools/common/test.go
  dev-tools/templates/notice/overrides.json
  go.mod
  go.sum
  magefile.go
  main.go
  tools/tools.go
  tools/version.go
Labels: Team:Elastic-Agent
