Repository elastic/elastic-agent-shipper, pull requests merged in 2022-06, with the labels that each got.

#47 Update metrics fields in queue monitoring
  NOTICE.txt
  go.mod
  go.sum
  monitoring/queuemon.go
  monitoring/queuemon_test.go
  monitoring/reporter/reporter.go
Labels: Team:Elastic-Agent-Data-Plane, v8.4.0

#51 Synchronize lint rules across repositories
  .golangci.yml
  dev-tools/templates/.golangci.yml
Labels: Team:Elastic-Agent-Data-Plane

#56 Update API protocol
  api/shipper.pb.go
  api/shipper.proto
  server/server.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane, v8.4.0

#59 Add V1 controller and spec support to the shipper
  NOTICE.txt
  cmd/cmd.go
  config/config.go
  config/config_test.go
  dev-tools/set_docs_version
  dev-tools/set_version
  docs/version.asciidoc
  elastic-agent-shipper.yml
  go.mod
  go.sum
  magefile.go
  monitoring/queuemon.go
  monitoring/reporter/expvar/expvars.go
  monitoring/reporter/log/log.go
  output/console.go
  queue/queue.go
  server/agent_client.go
  server/client_test.go
  server/run.go
  server/server.go
  version/version.go
Labels: Team:Elastic-Agent-Data-Plane, v8.4.0

#67 Add failing build and flaky test detector
  .ci/Jenkinsfile
Labels: Team:Elastic-Agent-Data-Plane

#69 Add Timestamp support in Struct of protobuf
  api/messages/ack.pb.go
  api/messages/ack.proto
  api/messages/publish.pb.go
  api/messages/publish.proto
  api/messages/struct.pb.go
  api/messages/struct.proto
  api/shipper.pb.go
  api/shipper.proto
  api/shipper_grpc.pb.go
  magefile.go
  output/console.go
  queue/queue.go
  queue/queue_test.go
  server/server.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane
