Repository elastic/elastic-agent-shipper, pull requests merged in 2022-11, with the labels that each got.

#155 Fix package naming to include version
  magefile.go
Labels: bug, Team:Elastic-Agent, Team:Elastic-Agent-Control-Plane, backport-skip

#100 ci: enable DRA for main and branches
  .ci/Jenkinsfile
  magefile.go
Labels: backport-v8.5.0

#158 Bump up version to 8.6.0
  tools/version.go
Labels: bug, Team:Elastic-Agent, Team:Elastic-Agent-Control-Plane, backport-skip

#162 [automation] Update go release version 1.18.8
  .go-version
  .golangci.yml
Labels: automation, dependency, backport-skip

#164 Add versioning information
  .goreleaser.yaml
  cmd/cmd.go
  cmd/version.go
  tools/helper.go
Labels: enhancement, Team:Elastic-Agent, Team:Elastic-Agent-Control-Plane, backport-skip

#154 add suport for queue metrics in shipper
  NOTICE.txt
  controller/controller_client.go
  go.mod
  go.sum
  monitoring/queuemon.go
Labels: Team:Elastic-Agent, v8.6.0

#170 Add support for codecs
  output/kafka/config.go
  output/kafka/kafka.go
Labels: Team:Elastic-Agent

#177 backport: Add 8.6 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, release

#184 [Release] Update version to 8.5.3
  tools/version.go
Labels: Team:Automation, release

#188 Remove deprecated CI option
  .github/workflows/golangci-lint.yml
Labels: bug

#189 Update the client version
  NOTICE.txt
  go.mod
  go.sum
Labels: bug, Team:Elastic-Agent-Data-Plane

#190 Fixed gorelease definition
  .goreleaser.yaml
Labels: bug, Team:Elastic-Agent, backport-skip

#193 actions: use go-version-file: .go-version
  .github/workflows/golangci-lint.yml
Labels: backport-v8.5.0, backport-v8.6.0
