Repository elastic/elastic-agent-shipper, pull requests merged in 2022-05, with the labels that each got.

#35 Update proto docs and clarify edge cases
  api/shipper.pb.go
  api/shipper.proto
  api/shipper_grpc.pb.go
Labels: documentation, Team:Elastic-Agent-Data-Plane

#37 Mark all code as owned by the data plane team
  .github/CODEOWNERS
Labels: Team:Elastic-Agent-Data-Plane

#39 Update go release version to 1.17.10
  .ci/bump-go-release-version.sh
  .go-version
  .golangci.yml
Labels: enhancement

#40 Add package and API skeleton for internal queue
  monitoring/queuemon.go
  monitoring/queuemon_test.go
  queue/queue.go
  server/run.go
  server/server.go
Labels: Team:Elastic-Agent-Data-Plane
