Repository elastic/elastic-agent-shipper, pull requests merged in 2022-10, with the labels that each got.

#135 [automation] Update go release version 1.18.7
  .go-version
  .golangci.yml
Labels: automation, dependency, backport-skip

#139 Add dependencies generation
  dev-tools/common.bash
  dev-tools/dependencies-report
  dev-tools/run_with_go_ver
  dev-tools/templates/dependencies.csv.tmpl
  magefile.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-skip

#140 Dependencies script comment cleanup
  dev-tools/run_with_go_ver
  magefile.go
Labels: bug, Team:Elastic-Agent-Control-Plane
