Repository elastic/elastic-agent-shipper, pull requests merged in 2022-09, with the labels that each got.

#105 [automation] Update go release version 1.18.6
  .go-version
  .golangci.yml
Labels: automation, dependency, backport-skip

#107 mergify: enable configuration
  .mergify.yml
Labels: Team:Automation, automation, backport-skip

#110 backport: Add 8.5 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, release

#111 [Release] Update version to 8.5.1
  tools/version.go
Labels: Team:Automation, release

#127 switch to stdlib errors package
  .golangci.yml
  NOTICE.txt
  dev-tools/common/common.go
  dev-tools/common/test.go
  go.mod
  magefile.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#126 Packaging for elastic agent
  README.md
  elastic-agent-shipper.spec.yml
  magefile.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane

#131 Added support for 'mage package:all'
  magefile.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane

#133 ci: honour the SNAPSHOT variable to fix the build errors in the CI
  .ci/Jenkinsfile
Labels: backport-v8.5.0
