Repository elastic/elastic-agent-shipper, pull requests merged in 2022-12, with the labels that each got.

#187 Migrate the elasticsearch output to go-elasticsearch
  NOTICE.txt
  controller/runner.go
  go.mod
  go.sum
  output/console.go
  output/elasticsearch/bulk.go
  output/elasticsearch/callbacks.go
  output/elasticsearch/client.go
  output/elasticsearch/config.go
  output/elasticsearch/json_read.go
  output/elasticsearch/output.go
  output/elasticsearch/util.go
  output/kafka/output.go
  queue/queue.go
  queue/queue_test.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#201 [automation] Update go release version 1.18.9
  .go-version
  .golangci.yml
Labels: automation, dependency, backport-skip

#204 Include tags in checkouts to fix release builds.
  .ci/Jenkinsfile
Labels: Team:Elastic-Agent

#206 Kafka integration test
  output/kafka/client.go
  output/kafka/config.go
  output/kafka/kafka_integration_test.go
  testing/environments/kafka/docker-compose.yml
  testing/environments/kafka/dockerfiles/Dockerfile
  testing/environments/kafka/dockerfiles/README.md
  testing/environments/kafka/dockerfiles/certs/broker-cert
  testing/environments/kafka/dockerfiles/certs/broker-cert-signed
  testing/environments/kafka/dockerfiles/certs/broker.keystore.jks
  testing/environments/kafka/dockerfiles/certs/ca-cert
  testing/environments/kafka/dockerfiles/certs/ca-cert.srl
  testing/environments/kafka/dockerfiles/certs/ca-key
  testing/environments/kafka/dockerfiles/certs/client.truststore.jks
  testing/environments/kafka/dockerfiles/healthcheck.sh
  testing/environments/kafka/dockerfiles/run.sh
Labels: Team:Elastic-Agent

#207 Add an Elasticsearch docker configuration for testing
  testing/environments/elasticsearch/docker-compose.yml
  testing/environments/elasticsearch/elasticsearch_config.yml
  testing/environments/elasticsearch/pki/ca/ca.crt
  testing/environments/elasticsearch/pki/ca/ca.key
  testing/environments/elasticsearch/pki/elasticsearchssl/elasticsearchssl.crt
  testing/environments/elasticsearch/pki/elasticsearchssl/elasticsearchssl.key
  testing/environments/elasticsearch/pki/generate_pki.sh
  testing/environments/elasticsearch/roles.yml
  testing/environments/elasticsearch/users
  testing/environments/elasticsearch/users_roles
Labels: enhancement

#208 Helpers for starting/stopping containers during tests
  testing/environments/environments.go
Labels: enhancement, Team:Elastic-Agent
