Repository elastic/elastic-agent-shipper, pull requests merged in 2023-02, with the labels that each got.

#236 backport: Add 8.7 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, release

#238 Bump version to 8.8.0
  tools/version.go
Labels: backport-skip

#185 Update the shipper to work with the elastic-agent
  NOTICE.txt
  cmd/cmd.go
  config/config.go
  config/config_test.go
  controller/controller_client.go
  controller/controller_client_test.go
  controller/helpers.go
  controller/run.go
  controller/run_test.go
  controller/runner.go
  controller/units.go
  dev-tools/common/common.go
  dev-tools/common/test.go
  go.mod
  go.sum
  grpcserver/inputhandler.go
  grpcserver/server.go
  grpcserver/server_test.go
  output/elasticsearch/config.go
  output/elasticsearch/output.go
  publisherserver/server.go
  server/config.go
Labels: enhancement, Team:Elastic-Agent, v8.6.0

#239 Add Elasticsearch output status reporter
  controller/controller_client.go
  controller/helpers.go
  controller/run.go
  output/elasticsearch/config.go
  output/elasticsearch/config_test.go
  output/elasticsearch/output.go
  output/elasticsearch/watcher.go
  publisherserver/server.go
Labels: enhancement, Team:Elastic-Agent

#249 Update shipper to use fastjson, new shipper client version
  NOTICE.txt
  go.mod
  go.sum
  output/elasticsearch/output.go
  output/elasticsearch/output_test.go
Labels: bug, Team:Elastic-Agent, backport-v8.7.0

#250 Fix test under darwin
  controller/run.go
  controller/run_test.go
Labels: bug

#251 Fix TestChangeOutputType controller test
  controller/controller_client_test.go
Labels: bug

#241 [Release] Update version to 8.6.3
  tools/version.go
Labels: Team:Automation, release

#254 change to v2 spec file
  elastic-agent-shipper.spec.yml
Labels: bug, Team:Elastic-Agent

#260 Fix position of done call in Log level test
  controller/controller_client_test.go
Labels: bug, Team:Elastic-Agent
