Repository elastic/elastic-agent-shipper, pull requests merged in 2023-04, with the labels that each got.

#293 Propagate the mage verbose flag to gorelease
  magefile.go
Labels: backport-skip

#296 Add infinite retry, fix monitoring
  NOTICE.txt
  go.mod
  monitoring/queuemon.go
  output/elasticsearch/config.go
  output/elasticsearch/config_test.go
  output/elasticsearch/output.go
  output/elasticsearch/watcher.go
  output/elasticsearch/watcher_test.go
Labels: Team:Elastic-Agent

#302 Update elastic-agent-client to latest.
  NOTICE.txt
  controller/controller_client.go
  controller/units.go
  go.mod
  go.sum
Labels: Team:Elastic-Agent

#305 [Release] update version to 8.9
  tools/version.go
Labels: release
