Repository elastic/elastic-agent-shipper, pull requests merged in 2023-06, with the labels that each got.

#312 [Release] Update version to 8.8.2
  tools/version.go
Labels: Team:Automation, release

#313 [Automation] Bump Golang version to 1.19.10
  .go-version
  .golangci.yml
Labels: automation, backport-skip, backport-v8.8.0

#316 backport: Add 8.9 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, release

#318 Update version.go
  tools/version.go
Labels: backport-skip

#315 [Release] Update version to 8.8.3
  tools/version.go
Labels: Team:Automation, release
