Repository elastic/elastic-agent-shipper, pull requests merged in 2023-01, with the labels that each got.

#192 [Release] Update version to 8.5.4
  tools/version.go
Labels: Team:Automation, release

#178 [Release] Update version to 8.6.1
  tools/version.go
Labels: Team:Automation, release

#214 Update copyright to include 2023 and upgrade elastic-agent-libs.
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent, backport-v8.6.0

#216 [automation] Update go release version 1.18.10
  .go-version
  .golangci.yml
Labels: automation, dependency, backport-skip, backport-v8.6.0

#220 action: use opentelemetry composite action
  .github/workflows/opentelemetry.yml
Labels: Team:Automation, automation, backport-v8.6.0

#210 POC for logstash output
  NOTICE.txt
  controller/runner.go
  elastic-agent-shipper.yml
  go.mod
  go.sum
  integration/console_test.go
  integration/integration_test.go
  integration/logstash_test.go
  output/logstash/client.go
  output/logstash/client_test.go
  output/logstash/config.go
  output/logstash/config_test.go
  output/logstash/encode.go
  output/logstash/output.go
  output/logstash/sync.go
  output/output.go
  testing/environments/environments.go
  testing/environments/logstash/docker-compose.yml
  testing/environments/logstash/pipeline/default.conf
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#229 [Release] Update version to 8.6.2
  tools/version.go
Labels: Team:Automation, release

#227 Enable batch config settings in the ES output
  elastic-agent-shipper.yml
  output/elasticsearch/config.go
  output/elasticsearch/config_test.go
  output/elasticsearch/output.go
Labels: enhancement, Team:Elastic-Agent
