Repository elastic/elastic-agent-shipper, pull requests merged in 2023-03, with the labels that each got.

#235 [updatecli][shell] Bump version to 1.19
  .github/workflows/golangci-lint.yml
  .go-version
  .golangci.yml
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-skip

#270 update shipper client, fix action type in ES output
  NOTICE.txt
  go.mod
  go.sum
  output/elasticsearch/output.go
  output/kafka/partition.go
  output/kafka/util.go
  queue/queue_test.go
Labels: bug, Team:Elastic-Agent

#277 Add custom event encoder for Elasticsearch output
  NOTICE.txt
  go.mod
  go.sum
  output/elasticsearch/event.go
  output/elasticsearch/event_test.go
  output/elasticsearch/output.go
Labels: bug, Team:Elastic-Agent

#278 Remove check for global log level in test
  controller/controller_client_test.go
Labels: Team:Elastic-Agent

#281 Increase max RPC size to 64MB
  NOTICE.txt
  go.mod
  go.sum
  grpcserver/inputhandler.go
Labels: bug, Team:Elastic-Agent

#237 [Release] Update version to 8.7.1
  tools/version.go
Labels: Team:Automation, release
