Repository elastic/elastic-agent-shipper, pull requests merged in 2023-05, with the labels that each got.

#308 [Automation] Bump Golang version to 1.19.9
  .go-version
  .golangci.yml
Labels: automation, backport-skip, backport-v8.8.0

#303 backport: Add 8.8 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, release

#304 [Release] Update version to 8.8.1
  tools/version.go
Labels: Team:Automation, release
